# Generated by Django 5.2.6 on 2025-11-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_firebase_uid_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_receiver',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='donor', max_length=20),
        ),
    ]
