# Generated by Django 5.2.6 on 2025-10-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_ngoverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoverification',
            old_name='ngo',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ngoverification',
            name='reviewed_at',
        ),
    ]
