# Generated by Django 5.2.6 on 2025-10-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_rename_ngo_ngoverification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
