# Generated by Django 5.2.6 on 2025-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_ngoverification_reviewed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='images',
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
