# Generated by Django 5.2.6 on 2025-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_remove_donation_images_donation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='image',
        ),
        migrations.AddField(
            model_name='donation',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
