# Generated by Django 5.2.6 on 2025-10-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_remove_donation_image_donation_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
